import type { Item, ItemShape, ItemType, ElementType, ItemRarity } from './types';
import { RARITY_WEIGHTS, ITEM_TYPE_COLORS, ELEMENT_COLORS } from './constants';

const SHAPES: Record<string, ItemShape> = {
  single: [{ dx: 0, dy: 0 }],
  vertical2: [{ dx: 0, dy: 0 }, { dx: 0, dy: 1 }],
  vertical3: [{ dx: 0, dy: 0 }, { dx: 0, dy: 1 }, { dx: 0, dy: 2 }],
  vertical4: [{ dx: 0, dy: 0 }, { dx: 0, dy: 1 }, { dx: 0, dy: 2 }, { dx: 0, dy: 3 }],
  horizontal2: [{ dx: 0, dy: 0 }, { dx: 1, dy: 0 }],
  horizontal3: [{ dx: 0, dy: 0 }, { dx: 1, dy: 0 }, { dx: 2, dy: 0 }],
  horizontal4: [{ dx: 0, dy: 0 }, { dx: 1, dy: 0 }, { dx: 2, dy: 0 }, { dx: 3, dy: 0 }],
  square2x2: [{ dx: 0, dy: 0 }, { dx: 1, dy: 0 }, { dx: 0, dy: 1 }, { dx: 1, dy: 1 }],
  square3x3: [
    { dx: 0, dy: 0 }, { dx: 1, dy: 0 }, { dx: 2, dy: 0 },
    { dx: 0, dy: 1 }, { dx: 1, dy: 1 }, { dx: 2, dy: 1 },
    { dx: 0, dy: 2 }, { dx: 1, dy: 2 }, { dx: 2, dy: 2 },
  ],
  L_shape: [{ dx: 0, dy: 0 }, { dx: 0, dy: 1 }, { dx: 0, dy: 2 }, { dx: 1, dy: 2 }],
  T_shape: [{ dx: 0, dy: 0 }, { dx: 1, dy: 0 }, { dx: 2, dy: 0 }, { dx: 1, dy: 1 }],
  Z_shape: [{ dx: 0, dy: 0 }, { dx: 1, dy: 0 }, { dx: 1, dy: 1 }, { dx: 2, dy: 1 }],
  S_shape: [{ dx: 1, dy: 0 }, { dx: 2, dy: 0 }, { dx: 0, dy: 1 }, { dx: 1, dy: 1 }],
};

function makeItem(
  base: Partial<Item> & {
    id: string;
    name: string;
    description: string;
    type: ItemType;
    shape: ItemShape;
    icon: string;
    rarity: ItemRarity;
    element?: ElementType;
    stats?: Item['stats'];
    adjacencyEffects?: Item['adjacencyEffects'];
    effects?: Item['effects'];
    price?: number;
  }
): Item {
  return {
    id: base.id,
    name: base.name,
    description: base.description,
    shape: base.shape,
    rotation: 0,
    rarity: base.rarity,
    type: base.type,
    element: base.element || 'none',
    stats: base.stats || {},
    effects: base.effects || [{ type: 'passive', description: base.description }],
    adjacencyEffects: base.adjacencyEffects,
    position: null,
    icon: base.icon,
    color: base.color || ITEM_TYPE_COLORS[base.type],
    price: base.price,
  };
}

export const ITEM_TEMPLATES: Item[] = [
  makeItem({
    id: 'iron_sword',
    name: '铁剑',
    description: '普通的铁制长剑，可靠的伙伴。',
    type: 'weapon',
    shape: SHAPES.vertical3,
    icon: '🗡️',
    rarity: 'common',
    stats: { attack: 8 },
    color: '#8b7355',
    price: 25,
  }),
  makeItem({
    id: 'short_sword',
    name: '短剑',
    description: '轻便的短兵器，适合快速攻击。',
    type: 'weapon',
    shape: SHAPES.vertical2,
    icon: '🔪',
    rarity: 'common',
    stats: { attack: 5 },
    color: '#8b7355',
    price: 15,
  }),
  makeItem({
    id: 'great_sword',
    name: '双手剑',
    description: '需要双手才能挥舞的重型武器。',
    type: 'weapon',
    shape: SHAPES.vertical4,
    icon: '⚔️',
    rarity: 'rare',
    stats: { attack: 15, critChance: 0.1 },
    color: '#6b4423',
    price: 80,
  }),
  makeItem({
    id: 'flame_sword',
    name: '火焰剑',
    description: '燃烧着火焰的魔法长剑。',
    type: 'weapon',
    shape: SHAPES.vertical3,
    icon: '🔥',
    rarity: 'rare',
    element: 'fire',
    stats: { attack: 12 },
    color: '#e63946',
    adjacencyEffects: [{
      effect: 'enchant',
      value: 5,
      description: '火焰附加：造成额外5点火焰伤害',
    }],
    price: 100,
  }),
  makeItem({
    id: 'ice_sword',
    name: '寒冰剑',
    description: '散发寒气的冰霜武器。',
    type: 'weapon',
    shape: SHAPES.vertical3,
    icon: '❄️',
    rarity: 'rare',
    element: 'ice',
    stats: { attack: 10 },
    color: '#48cae4',
    adjacencyEffects: [{
      effect: 'enchant',
      value: 3,
      description: '冰霜效果：减速敌人30%',
    }],
    price: 100,
  }),
  makeItem({
    id: 'thunder_sword',
    name: '雷剑',
    description: '蕴含雷电之力的魔法武器。',
    type: 'weapon',
    shape: SHAPES.vertical3,
    icon: '⚡',
    rarity: 'epic',
    element: 'lightning',
    stats: { attack: 14, critChance: 0.15 },
    color: '#ffd60a',
    price: 200,
  }),
  makeItem({
    id: 'shadow_blade',
    name: '暗影之刃',
    description: '汲取暗影之力的诡异武器。',
    type: 'weapon',
    shape: SHAPES.vertical3,
    icon: '🗡️',
    rarity: 'epic',
    element: 'dark',
    stats: { attack: 13 },
    color: '#9d4edd',
    adjacencyEffects: [{
      effect: 'enchant',
      value: 3,
      description: '吸血：造成伤害的20%转化为生命',
    }],
    price: 250,
  }),
  makeItem({
    id: 'holy_sword',
    name: '圣光剑',
    description: '闪耀着神圣光芒的正义之剑。',
    type: 'weapon',
    shape: SHAPES.vertical3,
    icon: '✨',
    rarity: 'legendary',
    element: 'holy',
    stats: { attack: 18, critChance: 0.2 },
    color: '#ffd6a5',
    adjacencyEffects: [{
      effect: 'enchant',
      value: 8,
      description: '神圣制裁：对亡灵敌人造成双倍伤害',
    }],
    price: 500,
  }),

  makeItem({
    id: 'leather_shield',
    name: '皮盾',
    description: '简单的皮革盾牌，提供基础防御。',
    type: 'armor',
    shape: SHAPES.square2x2,
    icon: '🛡️',
    rarity: 'common',
    stats: { defense: 4 },
    color: '#8b7355',
    price: 30,
  }),
  makeItem({
    id: 'iron_shield',
    name: '铁盾',
    description: '坚固的铁制盾牌。',
    type: 'armor',
    shape: SHAPES.square2x2,
    icon: '🛡️',
    rarity: 'uncommon',
    stats: { defense: 7 },
    color: '#6b7280',
    price: 50,
  }),
  makeItem({
    id: 'tower_shield',
    name: '塔盾',
    description: '巨大的塔盾，提供极高防御但占用空间大。',
    type: 'armor',
    shape: SHAPES.square3x3,
    icon: '🛡️',
    rarity: 'rare',
    stats: { defense: 12 },
    color: '#4b5563',
    price: 120,
  }),
  makeItem({
    id: 'leather_armor',
    name: '皮甲',
    description: '轻便的皮革护甲。',
    type: 'armor',
    shape: SHAPES.T_shape,
    icon: '🥋',
    rarity: 'common',
    stats: { defense: 3, hp: 10 },
    color: '#8b7355',
    price: 35,
  }),
  makeItem({
    id: 'chain_mail',
    name: '锁子甲',
    description: '由金属环编织的护甲。',
    type: 'armor',
    shape: SHAPES.L_shape,
    icon: '🦺',
    rarity: 'uncommon',
    stats: { defense: 6, hp: 15 },
    color: '#6b7280',
    price: 60,
  }),
  makeItem({
    id: 'plate_armor',
    name: '板甲',
    description: '重型板甲，提供极高防护。',
    type: 'armor',
    shape: SHAPES.square3x3,
    icon: '🛡️',
    rarity: 'rare',
    stats: { defense: 10, hp: 20 },
    color: '#4b5563',
    price: 150,
  }),
  makeItem({
    id: 'dragon_scale_armor',
    name: '龙鳞甲',
    description: '用巨龙鳞片制成的传说护甲。',
    type: 'armor',
    shape: SHAPES.square3x3,
    icon: '🛡️',
    rarity: 'legendary',
    element: 'fire',
    stats: { defense: 15, hp: 30 },
    color: '#e63946',
    price: 500,
  }),

  makeItem({
    id: 'health_potion',
    name: '治疗药水',
    description: '恢复生命值的红色药水。',
    type: 'potion',
    shape: SHAPES.single,
    icon: '🧪',
    rarity: 'common',
    stats: { hp: 30 },
    color: '#e63946',
    stackable: true,
    maxStack: 5,
    price: 20,
  }),
  makeItem({
    id: 'greater_health_potion',
    name: '大治疗药水',
    description: '恢复大量生命值的药水。',
    type: 'potion',
    shape: SHAPES.vertical2,
    icon: '🧪',
    rarity: 'uncommon',
    stats: { hp: 60 },
    color: '#dc2626',
    price: 45,
  }),
  makeItem({
    id: 'mana_potion',
    name: '法力药水',
    description: '恢复法力的蓝色药水。',
    type: 'potion',
    shape: SHAPES.single,
    icon: '🧪',
    rarity: 'common',
    stats: { mana: 25 },
    color: '#3b82f6',
    stackable: true,
    maxStack: 5,
    price: 20,
  }),
  makeItem({
    id: 'stamina_potion',
    name: '体力药水',
    description: '恢复体力的绿色药水。',
    type: 'potion',
    shape: SHAPES.single,
    icon: '🧪',
    rarity: 'common',
    stats: { stamina: 30 },
    color: '#22c55e',
    stackable: true,
    maxStack: 5,
    price: 20,
  }),
  makeItem({
    id: 'strength_potion',
    name: '力量药水',
    description: '临时增加攻击力的药水。',
    type: 'potion',
    shape: SHAPES.single,
    icon: '🧪',
    rarity: 'uncommon',
    stats: { attack: 5 },
    color: '#f97316',
    price: 35,
  }),
  makeItem({
    id: 'antidote',
    name: '抗毒药剂',
    description: '解毒并提供毒素抗性。',
    type: 'potion',
    shape: SHAPES.single,
    icon: '🧪',
    rarity: 'uncommon',
    element: 'poison',
    stats: { hp: 10 },
    color: '#22c55e',
    price: 30,
  }),

  makeItem({
    id: 'ruby',
    name: '红宝石',
    description: '蕴含火焰之力的宝石。放在武器旁边可附魔。',
    type: 'gem',
    shape: SHAPES.single,
    icon: '💎',
    rarity: 'uncommon',
    element: 'fire',
    color: '#e63946',
    adjacencyEffects: [{
      targetType: 'weapon',
      effect: 'enchant',
      value: 5,
      description: '火焰附魔：相邻武器攻击力+5',
    }],
    price: 50,
  }),
  makeItem({
    id: 'sapphire',
    name: '蓝宝石',
    description: '蕴含冰霜之力的宝石。',
    type: 'gem',
    shape: SHAPES.single,
    icon: '💎',
    rarity: 'uncommon',
    element: 'ice',
    color: '#48cae4',
    adjacencyEffects: [{
      targetType: 'weapon',
      effect: 'enchant',
      value: 3,
      description: '冰霜附魔：相邻武器攻击力+3',
    }],
    price: 50,
  }),
  makeItem({
    id: 'topaz',
    name: '黄宝石',
    description: '蕴含雷电之力的宝石。',
    type: 'gem',
    shape: SHAPES.single,
    icon: '💎',
    rarity: 'rare',
    element: 'lightning',
    color: '#ffd60a',
    adjacencyEffects: [{
      targetType: 'weapon',
      effect: 'enchant',
      value: 4,
      description: '雷电附魔：相邻武器攻击力+4',
    }],
    price: 80,
  }),
  makeItem({
    id: 'emerald',
    name: '绿宝石',
    description: '蕴含剧毒之力的宝石。',
    type: 'gem',
    shape: SHAPES.single,
    icon: '💎',
    rarity: 'rare',
    element: 'poison',
    color: '#52b788',
    adjacencyEffects: [{
      targetType: 'weapon',
      effect: 'enchant',
      value: 2,
      description: '剧毒附魔：相邻武器附加持续伤害',
    }],
    price: 80,
  }),
  makeItem({
    id: 'diamond',
    name: '钻石',
    description: '最珍贵的宝石，提升所有相邻物品效果。',
    type: 'gem',
    shape: SHAPES.single,
    icon: '💎',
    rarity: 'epic',
    color: '#e0e7ff',
    adjacencyEffects: [{
      effect: 'boost',
      value: 2,
      description: '钻石辉光：所有相邻物品效果+2',
    }],
    price: 200,
  }),

  makeItem({
    id: 'ring_of_life',
    name: '生命戒指',
    description: '增加最大生命值的戒指。',
    type: 'ring',
    shape: SHAPES.single,
    icon: '💍',
    rarity: 'uncommon',
    stats: { hp: 20 },
    color: '#c9a227',
    adjacencyEffects: [{
      targetType: 'armor',
      effect: 'boost',
      value: 2,
      description: '戒指共鸣：相邻护甲防御+2',
    }],
    price: 60,
  }),
  makeItem({
    id: 'ring_of_power',
    name: '力量戒指',
    description: '增加攻击力的戒指。',
    type: 'ring',
    shape: SHAPES.single,
    icon: '💍',
    rarity: 'rare',
    stats: { attack: 4 },
    color: '#c9a227',
    price: 100,
  }),
  makeItem({
    id: 'ring_of_guardian',
    name: '守护戒指',
    description: '增加防御力的戒指。',
    type: 'ring',
    shape: SHAPES.single,
    icon: '💍',
    rarity: 'rare',
    stats: { defense: 5 },
    color: '#c9a227',
    price: 100,
  }),

  makeItem({
    id: 'bread',
    name: '面包',
    description: '恢复少量生命的食物。',
    type: 'food',
    shape: SHAPES.single,
    icon: '🍞',
    rarity: 'common',
    stats: { hp: 10 },
    color: '#d4a373',
    stackable: true,
    maxStack: 10,
    price: 5,
  }),
  makeItem({
    id: 'roast_meat',
    name: '烤肉',
    description: '美味的烤肉，恢复较多生命。',
    type: 'food',
    shape: SHAPES.horizontal2,
    icon: '🍖',
    rarity: 'uncommon',
    stats: { hp: 25 },
    color: '#b45309',
    price: 25,
  }),
  makeItem({
    id: 'magic_fruit',
    name: '魔法果实',
    description: '恢复法力和生命的神奇果实。',
    type: 'food',
    shape: SHAPES.single,
    icon: '🍇',
    rarity: 'rare',
    element: 'holy',
    stats: { hp: 20, mana: 15 },
    color: '#a855f7',
    price: 50,
  }),

  makeItem({
    id: 'iron_ingot',
    name: '铁锭',
    description: '锻造用的铁锭。',
    type: 'material',
    shape: SHAPES.horizontal2,
    icon: '🪨',
    rarity: 'common',
    color: '#6b7280',
    stackable: true,
    maxStack: 10,
    price: 15,
  }),
  makeItem({
    id: 'wood',
    name: '木材',
    description: '制作装备的基础材料。',
    type: 'material',
    shape: SHAPES.horizontal3,
    icon: '🪵',
    rarity: 'common',
    color: '#8b7355',
    stackable: true,
    maxStack: 10,
    price: 10,
  }),
  makeItem({
    id: 'leather',
    name: '皮革',
    description: '制作皮甲的材料。',
    type: 'material',
    shape: SHAPES.square2x2,
    icon: '🟫',
    rarity: 'common',
    color: '#8b7355',
    stackable: true,
    maxStack: 5,
    price: 20,
  }),
  makeItem({
    id: 'magic_crystal',
    name: '魔法水晶',
    description: '蕴含魔力的水晶，制作魔法装备的材料。',
    type: 'material',
    shape: SHAPES.single,
    icon: '🔮',
    rarity: 'rare',
    color: '#9d4edd',
    price: 60,
  }),
  makeItem({
    id: 'dragon_scale',
    name: '龙之鳞片',
    description: '巨龙的鳞片，极其稀有。',
    type: 'material',
    shape: SHAPES.square2x2,
    icon: '🐉',
    rarity: 'legendary',
    element: 'fire',
    color: '#e63946',
    price: 300,
  }),

  makeItem({
    id: 'fireball_scroll',
    name: '火球术卷轴',
    description: '学习火球术的魔法卷轴。',
    type: 'scroll',
    shape: SHAPES.horizontal2,
    icon: '📜',
    rarity: 'uncommon',
    element: 'fire',
    stats: { attack: 8 },
    color: '#e63946',
    price: 40,
  }),
  makeItem({
    id: 'frost_nova_scroll',
    name: '冰霜新星卷轴',
    description: '学习冰霜新星的魔法卷轴。',
    type: 'scroll',
    shape: SHAPES.horizontal2,
    icon: '📜',
    rarity: 'rare',
    element: 'ice',
    stats: { attack: 10 },
    color: '#48cae4',
    price: 80,
  }),
  makeItem({
    id: 'heal_scroll',
    name: '治疗术卷轴',
    description: '学习治疗术的魔法卷轴。',
    type: 'scroll',
    shape: SHAPES.horizontal2,
    icon: '📜',
    rarity: 'uncommon',
    element: 'holy',
    stats: { hp: 20 },
    color: '#ffd6a5',
    price: 40,
  }),
  makeItem({
    id: 'teleport_scroll',
    name: '传送卷轴',
    description: '可以传送回营地的卷轴。',
    type: 'scroll',
    shape: SHAPES.single,
    icon: '📜',
    rarity: 'rare',
    color: '#9d4edd',
    price: 100,
  }),
];

export function getItemById(id: string): Item | undefined {
  return ITEM_TEMPLATES.find((item) => item.id === id);
}

export function getRandomItemIdByRarity(rarity?: ItemRarity): string {
  let pool = ITEM_TEMPLATES;
  if (rarity) {
    pool = ITEM_TEMPLATES.filter((item) => item.rarity === rarity);
  }
  if (pool.length === 0) pool = ITEM_TEMPLATES;
  const weights = pool.map((item) => RARITY_WEIGHTS[item.rarity]);
  const totalWeight = weights.reduce((a, b) => a + b, 0);
  let random = Math.random() * totalWeight;
  for (let i = 0; i < pool.length; i++) {
    random -= weights[i];
    if (random <= 0) return pool[i].id;
  }
  return pool[0].id;
}

export function createItemInstance(templateId: string): Item | null {
  const template = getItemById(templateId);
  if (!template) return null;
  return {
    ...template,
    id: `${template.id}_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`,
    position: null,
    rotation: 0,
  };
}

export function getItemsByType(type: ItemType): Item[] {
  return ITEM_TEMPLATES.filter((item) => item.type === type);
}

export { SHAPES };
