import type { PhysicsConfig, Colors } from '../types/game';

export const PHYSICS: PhysicsConfig = {
  FRICTION: 0.992,
  RESTITUTION_BALL: 0.95,
  RESTITUTION_WALL: 0.85,
  MIN_VELOCITY: 0.05,
  BALL_RADIUS: 12,
  TABLE_WIDTH: 800,
  TABLE_HEIGHT: 400,
  CUSHION_WIDTH: 24,
  POCKET_RADIUS: 24,
  MAX_POWER: 18,
  POWER_RATE: 0.015,
};

export const COLORS: Colors = {
  TABLE_FELT: '#0B5D1E',
  TABLE_FELT_DARK: '#084215',
  CUSHION: '#8B4513',
  CUSHION_DARK: '#5D2E0C',
  POCKET: '#0a0a0a',
  BALL_WHITE: '#FFFFFF',
  BALL_YELLOW: '#FFD700',
  BALL_BLUE: '#0066CC',
  BALL_RED: '#CC0000',
  BALL_PURPLE: '#660099',
  BALL_ORANGE: '#FF6600',
  BALL_GREEN: '#009933',
  BALL_BROWN: '#8B4513',
  BALL_BLACK: '#1a1a1a',
  CUE: '#D2691E',
  CUE_TIP: '#F5DEB3',
  BACKGROUND: '#1a1a2e',
  TEXT: '#FFFFFF',
  TEXT_DARK: '#a0a0a0',
  ACCENT: '#FFD700',
  ERROR: '#FF4444',
};

export const BALL_COLORS: Record<number, string> = {
  0: COLORS.BALL_WHITE,
  1: COLORS.BALL_YELLOW,
  2: COLORS.BALL_BLUE,
  3: COLORS.BALL_RED,
  4: COLORS.BALL_PURPLE,
  5: COLORS.BALL_ORANGE,
  6: COLORS.BALL_GREEN,
  7: COLORS.BALL_BROWN,
  8: COLORS.BALL_BLACK,
  9: COLORS.BALL_YELLOW,
  10: COLORS.BALL_BLUE,
  11: COLORS.BALL_RED,
  12: COLORS.BALL_PURPLE,
  13: COLORS.BALL_ORANGE,
  14: COLORS.BALL_GREEN,
  15: COLORS.BALL_BROWN,
};

export const CANVAS_WIDTH = 960;
export const CANVAS_HEIGHT = 600;
export const TABLE_OFFSET_X = (CANVAS_WIDTH - PHYSICS.TABLE_WIDTH) / 2;
export const TABLE_OFFSET_Y = (CANVAS_HEIGHT - PHYSICS.TABLE_HEIGHT) / 2;

export const AIM_SPEED = 1.8;
export const MAX_CHARGE = 1.0;
export const MIN_CHARGE = 0.1;

export const AI_EASY_ERROR_ANGLE = 0.26;
export const AI_EASY_ERROR_POWER = 0.3;
export const AI_MEDIUM_ERROR_ANGLE = 0.087;
export const AI_MEDIUM_ERROR_POWER = 0.15;
export const AI_HARD_ERROR_ANGLE = 0.017;
export const AI_HARD_ERROR_POWER = 0.05;

export const AI_THINK_TIME = 1200;
