const PALETTE: Record<string, string> = {
  b: '#1a1a2e',
  d: '#2d2d5e',
  n: '#1a1a4e',
  s: '#e8c89e',
  k: '#c9a06c',
  r: '#c0392b',
  R: '#8b1a1a',
  w: '#e8e0d0',
  g: '#f1c40f',
  G: '#27ae60',
  D: '#1a5c32',
  B: '#8b4513',
  N: '#5d3a1a',
  p: '#6a1b9a',
  l: '#9f9f9f',
  y: '#6d6d6d',
  L: '#e74c3c',
  M: '#2d8b46',
  S: '#7f8c8d',
};

function sp(rows: string[]): string[][] {
  return rows.map(row => row.split(''));
}

const SPRITES = new Map<string, string[][]>([
  ['ninja_stand', sp([
    '....b.......',
    '...bbb......',
    '..bbbbb.....',
    '....sks.....',
    '...bbbbb....',
    '....bbb.....',
    '..ddddd.....',
    '.ddddddd....',
    '.ddrddddd...',
    '.ddddddd....',
    '..ddddd.....',
    '..ddddd.....',
    '...ddd......',
    '...bdb......',
    '..b...b.....',
    '.b.....b....',
  ])],

  ['ninja_run1', sp([
    '....b.......',
    '...bbb......',
    '..bbbbb.....',
    '....sks.....',
    '...bbbbb....',
    '....bbb.....',
    '..ddddd.....',
    '.ddddddd....',
    '.ddrddddd...',
    '.ddddddd....',
    '..ddddd.....',
    '..ddddd.....',
    '...ddd......',
    '..bd..b.....',
    '.b..........',
    '......b.....',
  ])],

  ['ninja_run2', sp([
    '....b.......',
    '...bbb......',
    '..bbbbb.....',
    '....sks.....',
    '...bbbbb....',
    '....bbb.....',
    '..ddddd.....',
    '.ddddddd....',
    '.ddrddddd...',
    '.ddddddd....',
    '..ddddd.....',
    '..ddddd.....',
    '...ddd......',
    '..b.d.b.....',
    '........b...',
    '............',
  ])],

  ['ninja_run3', sp([
    '....b.......',
    '...bbb......',
    '..bbbbb.....',
    '....sks.....',
    '...bbbbb....',
    '....bbb.....',
    '..ddddd.....',
    '.ddddddd....',
    '.ddrddddd...',
    '.ddddddd....',
    '..ddddd.....',
    '..ddddd.....',
    '...ddd......',
    '.....bd.....',
    '....b.......',
    '...b........',
  ])],

  ['ninja_jump', sp([
    '....b.......',
    '...bbb......',
    '..bbbbb.....',
    '....sks.....',
    '...bbbbb....',
    '.b.bbb.b....',
    '..ddddd.....',
    '.ddddddd....',
    '.ddrddddd...',
    '..ddddddd...',
    '...ddddd....',
    '....ddd.....',
    '...bd.db....',
    '..b.....b...',
    '............',
    '............',
  ])],

  ['ninja_float', sp([
    '....b.......',
    '...bbb......',
    '..bbbbb.....',
    '....sks.....',
    '...bbbbb....',
    '.b.bbb.b....',
    '..ddddd.....',
    '.ddddddd....',
    '.ddrddddd...',
    'ddddddddd...',
    'ddddddddd...',
    '.ddddddd....',
    '..ddddd.....',
    '...dbd......',
    '............',
    '............',
  ])],

  ['ninja_sword', sp([
    '....b.......',
    '...bbb......',
    '..bbbbb.....',
    '....sks.....',
    '...bbbbb....',
    '....bbb.....',
    '..ddddd.....',
    '.ddddddd....',
    '.ddrdddddlll',
    '.ddddddd.lll',
    '..ddddd..l..',
    '..ddddd.....',
    '...ddd......',
    '...bdb......',
    '..b...b.....',
    '.b.....b....',
  ])],

  ['ninja_throw', sp([
    '....b.......',
    '...bbb......',
    '..bbbbb.....',
    '....sks.....',
    '...bbbbb....',
    '....bbb.....',
    '..ddddd.....',
    '.ddddddd....',
    '.ddrdddddl..',
    '.ddddddd.l..',
    '..ddddd.l...',
    '..ddddd.....',
    '...ddd......',
    '...bdb......',
    '..b...b.....',
    '.b.....b....',
  ])],

  ['samurai', sp([
    '....RggR....',
    '...RRRRR....',
    '..RRgRRR....',
    '...sRRs.....',
    '..RRRRR.....',
    '.RRRRRRR....',
    '.rrRrrRr....',
    '.rrrrrrr....',
    '.rrrrrrrrr..',
    '.rrrrrrrrr..',
    '..rrrrrrr...',
    '..rrrrrrr...',
    '...rrrrr....',
    '...rr.rr....',
    '..RR...RR...',
    '.RR.....RR..',
    '............',
    '............',
  ])],

  ['ninja_enemy', sp([
    '....b.......',
    '...bbb......',
    '..bbbbb.....',
    '....sks.....',
    '...ppppp....',
    '....ppp.....',
    '..ppppp.....',
    '.ppppppp....',
    '.ppppppppp..',
    '.ppppppppp..',
    '..ppppp.....',
    '..ppppp.....',
    '...ppp......',
    '...bdb......',
    '..b...b.....',
    '.b.....b....',
  ])],

  ['thrower', sp([
    '............',
    '....b.......',
    '...bbb......',
    '..bbbbb.....',
    '....sks.....',
    '...DDDDD....',
    '..DDDDDD....',
    '.DDDDDDDD...',
    '..DDDDDD....',
    '...DDDDD....',
    '...DDDDD....',
    '....DDD.....',
    '....bD......',
    '...b..b.....',
    '............',
    '............',
  ])],

  ['monk', sp([
    '......kk........',
    '.....kkkk.......',
    '....kkkkkk......',
    '....skkkks......',
    '...kkkkkkkk.....',
    '...kkkkkkkk.....',
    '..BBBBBBBBB.....',
    '..BBBBBBBBBB....',
    '.BBBBBBBBBBBB...',
    '.BBBBBBBBBBBBB..',
    '.BBBBBBBBBBBBB..',
    '..BBBBBBBBBBB...',
    '..BBBBBBBBBBB...',
    '..BBBBBBBBBBB...',
    '...BBBBBBBBB....',
    '...BBB.BBB.BB...',
    '...BBB.BBB.BB...',
    '...BB...BB...BB.',
    '..BB....BB....BB',
    '..BB....BB....BB',
    '...BB...BB...BB.',
    '............BB..',
    '............BB..',
    '............BB..',
    '............BB..',
    '............BB..',
    '............BB..',
    '............BB..',
    '............BB..',
    '............BB..',
    '..........BB....',
    '..........BB....',
  ])],

  ['shadow_master', sp([
    '......nn..........',
    '.....nnnn.........',
    '....nnnnnn........',
    '....rnnnr.........',
    '...nnnnnnnn.......',
    '...nnnnnnnn.......',
    '..nnnnnnnnnn......',
    '.nnnnnnnnnnnn.....',
    '.nnnnnnnnnnnnnn...',
    '.nnnnnnnnnnnnnn...',
    '..nnnnnnnnnnnnn...',
    '..nnnnnnnnnnnnn...',
    '...nnnnnnnnnnn....',
    '...nnnnnnnnnnn....',
    '....nnnnnnnn......',
    '....nn..nn........',
    '...nnn..nnn.......',
    '..nn....nn........',
    '..nn....nn........',
    '..nn....nn........',
    '..nn....nn........',
    '..nn....nn........',
    '..nn....nn........',
    '..nn....nn........',
    '..nn....nn........',
    '..nn....nn........',
    '..nn....nn........',
    '..nn....nn........',
  ])],

  ['sorcerer', sp([
    '......b...........',
    '.....bbb..........',
    '....bbbbb.........',
    '....bnb...........',
    '...bbbbbb.........',
    '...bbbbbb.........',
    '..bbbbbbbbb.......',
    '.bbbbbbbbbbbb.....',
    '.bbbbbbbbbbbbb....',
    '.bbbbbbbbbbbbb....',
    '..bbbbbbbbbbbb....',
    '..bbbbbbbbbbbb....',
    '...bbbbbbbbbb.....',
    '...bbbbbbbbbb.....',
    '....bbbbbbbb......',
    '....bbb.bbb.......',
    '...bbbb..bbbb.....',
    '...bbb....bbb.....',
    '..bbb......bbb....',
    '..bbb......bbb....',
    '..bbb......bbb....',
    '..bbb......bbb....',
    '..bbb......bbb....',
    '..bbb......bbb....',
    '..bbb......bbb....',
    '..bbb......bbb....',
    '..bbb......bbb....',
    '..bbb......bbb....',
    '..bbb......bbb....',
    '..bbb......bbb....',
  ])],

  ['shuriken', sp([
    '...ll....',
    '..llll...',
    '.llllll..',
    '..llll...',
    '...ll....',
    '..llll...',
    '.llllll..',
    '..llll...',
  ])],

  ['enemy_shuriken', sp([
    '...RR....',
    '..RRRR...',
    '.RRRRRR..',
    '..RRRR...',
    '...RR....',
    '..RRRR...',
    '.RRRRRR..',
    '..RRRR...',
  ])],

  ['fireball', sp([
    '...L......',
    '..LLL.....',
    '.LLrrLL...',
    '.LrrrrrL..',
    'LrrggrrL..',
    'LrrggrrL..',
    '.LrrrrrL..',
    '.LLrrLL...',
    '..LLL.....',
    '...L......',
  ])],

  ['orb_white', sp([
    '....ww....',
    '..wwwwww..',
    '.wwwwwwww.',
    '.wwwwwwww.',
    'wwwwwwwwww',
    'wwwwwwwwww',
    '.wwwwwwww.',
    '.wwwwwwww.',
    '..wwwwww..',
    '....ww....',
  ])],

  ['orb_red', sp([
    '....rr....',
    '..rrrrrr..',
    '.rrrrrrrr.',
    '.rrrrrrrr.',
    'rrrrrrrrrr',
    'rrrrrrrrrr',
    '.rrrrrrrr.',
    '.rrrrrrrr.',
    '..rrrrrr..',
    '....rr....',
  ])],

  ['orb_green', sp([
    '....GG....',
    '..GGGGGG..',
    '.GGGGGGGG.',
    '.GGGGGGGG.',
    'GGGGGGGGGG',
    'GGGGGGGGGG',
    '.GGGGGGGG.',
    '.GGGGGGGG.',
    '..GGGGGG..',
    '....GG....',
  ])],

  ['scroll', sp([
    '..gggggggg..',
    '.gBBBggBBBg.',
    'gBBBBBBBBBg',
    'gBBBgggBBBg',
    'gBBgggggBBg',
    'gBBgggggBBg',
    'gBBgggggBBg',
    'gBBBgggBBBg',
    'gBBBBBBBBBg',
    '.gBBBggBBBg.',
    '..gggggggg..',
  ])],

  ['ribbon', sp([
    '..ww..',
    '.wwww.',
    'wwwwww',
    'wwppww',
    '.wwww.',
    '..ww..',
    '...w..',
    '......',
  ])],
]);

export class SpriteRenderer {
  private spriteCache = new Map<string, string[][]>();

  constructor() {
    SPRITES.forEach((pixels, name) => {
      this.spriteCache.set(name, pixels);
    });
  }

  drawSprite(ctx: CanvasRenderingContext2D, name: string, x: number, y: number, flipped: boolean = false, scale: number = 2): void {
    const pixels = this.spriteCache.get(name);
    if (!pixels) return;
    this.drawPixelArray(ctx, pixels, x, y, scale, flipped);
  }

  drawPixelArray(ctx: CanvasRenderingContext2D, pixels: string[][], x: number, y: number, scale: number = 2, flipped: boolean = false): void {
    const w = pixels[0]?.length ?? 0;
    for (let row = 0; row < pixels.length; row++) {
      for (let col = 0; col < w; col++) {
        const ch = pixels[row][col];
        if (ch === '.') continue;
        const color = PALETTE[ch];
        if (!color) continue;
        const dx = flipped ? x + (w - 1 - col) * scale : x + col * scale;
        const dy = y + row * scale;
        ctx.fillStyle = color;
        ctx.fillRect(dx, dy, scale, scale);
      }
    }
  }
}
